"""posts table

Revision ID: ccace290dc10
Revises: e40b0cc4c182
Create Date: 2023-07-26 22:24:25.113465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccace290dc10'
down_revision = 'e40b0cc4c182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('species', sa.String(length=64), nullable=True),
    sa.Column('dbh', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('note', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_dbh'), ['dbh'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_latitude'), ['latitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_longitude'), ['longitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_species'), ['species'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_timestamp'))
        batch_op.drop_index(batch_op.f('ix_post_species'))
        batch_op.drop_index(batch_op.f('ix_post_longitude'))
        batch_op.drop_index(batch_op.f('ix_post_latitude'))
        batch_op.drop_index(batch_op.f('ix_post_dbh'))

    op.drop_table('post')
    # ### end Alembic commands ###
